var schools = [
    { 'person': '钟江涛', 'school': '温州医科大学', 'major': '临床医学' },
    { 'person': '包相江', 'school': '江南大学', 'major': '光电与信息工程' },
    { 'person': '徐艳琪', 'school': '西南交通大学', 'major': '' },
    { 'person': '吕思佳', 'school': '大连海事大学', 'major': '' },
    { 'person': '凌瑞添', 'school': '东北大学秦皇岛分校', 'major': '机械类' },
    { 'person': '张晨昱', 'school': '长安大学', 'major': '' },
    { 'person': '朱天渝', 'school': '南京邮电大学', 'major': '材料化学' },
    { 'person': '邵琪雅', 'school': '杭州电子科技大学', 'major': '会计类' },
    { 'person': '颜祺淞', 'school': '杭州电子科技大学', 'major': '电子信息类（三位一体）' },
    { 'person': '陈黎莎', 'school': '杭州电子科技大学', 'major': ''},
    { 'person': '杨柳　', 'school': '浙江工商大学', 'major': '计算机专业' },
    { 'person': '王程可', 'school': '浙江工商大学', 'major': '电子信息类' },
    { 'person': '林银燕', 'school': '浙江工业大学', 'major': '' },
    { 'person': '郭颂', 'school': '太原理工大学', 'major': '' },
    { 'person': '郑虞颖', 'school': '宁波大学', 'major': '数学与应用数学' },
    { 'person': '沈汝奕', 'school': '浙江理工大学', 'major': '' },
    { 'person': '蒋霆龙', 'school': '浙江工业大学', 'major': '土木工程（中外合作办学）' },
    { 'person': '郑成锴', 'school': '四川农业大学成都校区', 'major': '' },
    { 'person': '宋琳　', 'school': '浙江传媒学院', 'major': '数字媒体技术' },
    { 'person': '张佳宁', 'school': '浙江农林大学', 'major': '计算机科学与技术（三位一体）' },
    { 'person': '罗浩天', 'school': '浙江海洋大学', 'major': '轮机工程' },
    { 'person': '谢易作', 'school': '浙江警官职业学院', 'major': '' },
    { 'person': '章楷豪', 'school': '西安电子科技大学', 'major': '电子信息类(物理与光电工程)' },
    { 'person': '宋珂源', 'school': '哈尔滨工业大学', 'major': '工科试验班(计算机与电子通信)' },
    { 'person': '张靖赟', 'school': '北京航空航天大学', 'major': '工科试验班类(信息类)' },
    { 'person': '陈虞滇', 'school': '南京师范大学', 'major': '' },
    { 'person': '顾子涵', 'school': '上海海事大学', 'major': '' },
    { 'person': '罗迈　', 'school': '伦敦大学学院', 'major': '艺术学院' }
];